incident-web:
  image: smebberson/alpine-nginx
  ports:
    - 8080:8080
  links:
    - incident-web-fpm:web
  volumes_from:
    - incident-web-fpm

incident-web-fpm:
  build: .
  ports:
      - 9000:9000
  volumes_from:
      - incident-web-data
  extra_hosts:
      - 'cachet:172.17.0.1'

incident-web-data:
  image: busybox
  command: chown 100:83 -Rf /var/www/health-checker-incident/app/data
  volumes:
    - ./config/parameters.yml:/var/www/health-checker-incident/app/config/parameters.yml:ro
    - /var/www/health-checker-incident/app/data
