incident-web:
  image: smebberson/alpine-nginx
  ports:
    - 8080:80
  links:
    - incident-web-fpm:web
  volumes:
    - ./nginx/health-checker-incident.conf:/etc/nginx/conf.d/default.conf:ro
  volumes_from:
    - incident-web-fpm

incident-web-fpm:
  build: .
  ports:
      - 9000:9000
  volumes_from:
      - incident-web-data

incident-web-data:
  image: busybox
  volumes:
    - /var/www/health-checker-incident/app/data